# -*- coding: utf-8 -*-
"""python_practice2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_10i5zEPl7_D04dGhJ2STa8D3bhGm_ja
"""

#Get keys[“name”, “age”] from dictionary and create new dictionary
animaldict={"name":"Dog",
           "age":5,
           "weight":30,
           'country':'usa',
           'city':'california'}
outDict={key:animaldict[key]for key in ["name","age"]}
outDict

#Program to delete set of keys from Dictionary ,keys to delete : [“name”, “age”]
animaldict={"name":"Dog",
           "age":5,
           "weight":30,
           'country':'usa',
           'city':'california'}
outDict={key:animaldict[key] for key in animaldict.keys()-  ["name",'age']}
outDict

#How to change the name of key in dictionary.
#Here we have to change the key “name “ to “Animalname” in nested dictionary.
animaldict = {
  "name": "Dog",
  "age":5,
  "Weight": 4,
  "Country": "US",
  "City":"California"
   
}
animaldict['Animalname']=animaldict.pop('name')
animaldict

#How to change the value of any key in nested dictionary
#here,we are changing the age of animal “cat” in nested “Animal 1” dictionary.
animaldict = {
  "animal":{
  "name": "Dog",
  "age":5,
},
    "animal1":{
  "name": "Cat",
  "age":2,
},
    "animal2":{
  "name": "Rabbit",
  "age":1,
},
}
animaldict['animal1']['age']=10
animaldict['animal2']['name']='cow'
print(animaldict)

#How to delete a key from Dictionary
fruitsDict={"apple":100,
            "banana":500,
            "Orange":700,
            "strawberries":900
            }
if 'apple' in fruitsDict:
  del fruitsDict['apple']
print('dict after deleting key=',fruitsDict)

#How to get min and max keys corresponding to min and max value in Dictionary
fruitsDict = {
  'Apple': 100,
  'Orange': 200,
  'Banana': 400,
  'pomegranate':600
}
print('min value key:', min(fruitsDict, key=fruitsDict.get))
print('max value key:', max(fruitsDict, key=fruitsDict.get))

#How to concatenate multiple dictionary in one
#Using for-loop and update() we can concatenate multiple dictionary in one
Fruits={'Apple':100,'banana':50,'pieapple':70}
Vegetables={'radish':400,'carrot':50,'potato':500}
Sweets={'barfi':600,'rosogola':600,'rasmalai':1000}
concate_Dict={}
for dict in (Fruits,Vegetables,Sweets):
  concate_Dict.update (dict)
print(concate_Dict)

#.How to sum all elements of Dictionary
fruits={"apple":100,'banana':200,'guava':250,'strwaberry':240,'chikus':87}
print('sum of all the values::',sum(fruits.values()))

#How to multiply all elements of Dictionary
FruitDict = {'Apple': 10, 'banana': 5,'orange':4,'Guava':6}
mutiply_res = 1
for key in FruitDict:    
    mutiply_res = mutiply_res * FruitDict[key]
 
print('mutiplication of dict elements = ',mutiply_res)

#How to sort a dictionary by key
FruitDict = {'Apple': 10, 'Banana': 5,'Orange':4,'Guava':6}
print('sorted dictionary=')
for key in sorted (FruitDict):
  print("%s:%s" % (key,FruitDict[key]))

TUPLES

#How to Sort List Of Tuples By Second Element
listoftuple=[('tuple',20,89),('list',67,87),('hello',4,54),('hi',8,76)]
print('original list of tuples=\n',listoftuple)
listoftuple.sort(key=lambda item:item[2])
print('list of tuples after sorting=\n',listoftuple)

#How to remove duplicate from list of tuples Using List comprehension
#a list of tuples
list_of_tuples= [("C#", 1), ("C#", 1), ("C++", 3), ("C++", 3), ("Python", 25), ("Rust", 30)]
print('list with duplicates=\n',list_of_tuples)
#removing the duplicates
unique_list_of_tuples=list(set([i for i in list_of_tuples]))
print('list after removing duplicates=\n',unique_list_of_tuples)

#How to remove duplicate from list of tuples using dict() function
listofTuples = [("C#" , 2), ("JS" , 3), ("C#" , 2),("GO" , 23),("Java" , 77)]
 
dictiwithlistof_tuples = dict(listofTuples)
print(dictiwithlistof_tuples)

#How do we reverse a string in Python?
String = "String Example" 
reversed=String[::-1]
print(reversed)

#Example to convert list to tuple.
listelement=['hello','list','how','are','you']
tuple=tuple(listelement)
print(tuple)

# How to convert two list to dictionary in Python?
subject=['maths','science','hindi','economics','history']
marks=[100,90,87,45,87]
student_score=dict(zip(subject,marks))
print(student_score)

#How To Filter A List of Given Elements In a List Of Tuples?Using lambda and list
listoftuple = [(1,2,'C#'),('Pyth',4),('Pyth',5,6),(7,8,),('Pyth',6)]
item = 'Pyth'
output = list(filter(lambda x:item in x, listoftuple))

#filltering the list of tuple
print('fliterring list of tuples =\n',output)

#Different Ways To Concatenate Tuples In Python.
#Sum() : To concatenate tuples into single/nested Tuples
tupleint=(1,2,3,4,5,6,7,8)
langtuple=('hello','hi','new')
concat_tup=sum((tupleint,langtuple),())
print('concatanate of tuple \n',concat_tup)

#Sum() to concatenate tuple into a nested tuple
tupleint=(1,2,3,4,5,6,7,8),
langtuple=('hello','hi','new'),
tuples_concatenate = sum((tupleint, langtuple), ())
print('tuple after concatanation= \n',tuples_concatenate)

#Write a program to create mixed datatype tuple in Pyth
mix_tuple=('hello',10.0,34,False,True)
print('here is mixed tuple=\n',mix_tuple)

Langtuple = (1, "C#", 3.4,'C++',False,True)
 
 
print( Langtuple[::5])
print( Langtuple[::2])
print( Langtuple[:-3])

#How to replace the last tuple value from list of tuples.
listoftuple=[(1.3,'hello',90),(4.7,'python',87),(9.5,'how',45),(45.0,'tolearn',78)]
print([tuple[:-1]+(100,) for tuple in listoftuple])